
package com.haier.openplatform.hac.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-09-17T16:05:11.752+08:00
 * Generated source version: 3.0.16
 * 
 */
public final class HacPrivilegeServiceClientPortType_HacPrivilegeServiceClientPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.hac.openplatform.haier.com/", "HacPrivilegeServiceClient");

    private HacPrivilegeServiceClientPortType_HacPrivilegeServiceClientPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HacPrivilegeServiceClient.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HacPrivilegeServiceClient ss = new HacPrivilegeServiceClient(wsdlURL, SERVICE_NAME);
        HacPrivilegeServiceClientPortType port = ss.getHacPrivilegeServiceClientPort();  
        
        {
        System.out.println("Invoking postponePrivilegesToUser...");
        java.lang.String _postponePrivilegesToUser_arg0 = "";
        java.lang.String _postponePrivilegesToUser_arg1 = "";
        java.lang.String _postponePrivilegesToUser_arg2 = "";
        java.lang.String _postponePrivilegesToUser_arg3 = "";
        java.lang.String _postponePrivilegesToUser_arg4 = "";
        java.lang.String _postponePrivilegesToUser_arg5 = "";
        java.lang.String _postponePrivilegesToUser_arg6 = "";
        com.haier.openplatform.hac.service.ExecuteResult _postponePrivilegesToUser__return = port.postponePrivilegesToUser(_postponePrivilegesToUser_arg0, _postponePrivilegesToUser_arg1, _postponePrivilegesToUser_arg2, _postponePrivilegesToUser_arg3, _postponePrivilegesToUser_arg4, _postponePrivilegesToUser_arg5, _postponePrivilegesToUser_arg6);
        System.out.println("postponePrivilegesToUser.result=" + _postponePrivilegesToUser__return);


        }
        {
        System.out.println("Invoking getPrivilegeData...");
        java.lang.String _getPrivilegeData_arg0 = "";
        java.lang.String _getPrivilegeData_arg1 = "";
        java.lang.Long _getPrivilegeData_arg2 = null;
        java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> _getPrivilegeData__return = port.getPrivilegeData(_getPrivilegeData_arg0, _getPrivilegeData_arg1, _getPrivilegeData_arg2);
        System.out.println("getPrivilegeData.result=" + _getPrivilegeData__return);


        }
        {
        System.out.println("Invoking searchHacDataPrivilegeByUserCode...");
        com.haier.openplatform.hac.service.HacDataPrivilegeAppDTO _searchHacDataPrivilegeByUserCode_arg0 = null;
        java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> _searchHacDataPrivilegeByUserCode__return = port.searchHacDataPrivilegeByUserCode(_searchHacDataPrivilegeByUserCode_arg0);
        System.out.println("searchHacDataPrivilegeByUserCode.result=" + _searchHacDataPrivilegeByUserCode__return);


        }
        {
        System.out.println("Invoking addUserDataPrivilege...");
        java.util.List<com.haier.openplatform.hac.service.HacUserDataPrivilegeRelDTO> _addUserDataPrivilege_arg0 = null;
        boolean _addUserDataPrivilege__return = port.addUserDataPrivilege(_addUserDataPrivilege_arg0);
        System.out.println("addUserDataPrivilege.result=" + _addUserDataPrivilege__return);


        }
        {
        System.out.println("Invoking getLastAppVerion...");
        java.lang.String _getLastAppVerion_arg0 = "";
        java.lang.String _getLastAppVerion__return = port.getLastAppVerion(_getLastAppVerion_arg0);
        System.out.println("getLastAppVerion.result=" + _getLastAppVerion__return);


        }
        {
        System.out.println("Invoking searchHacDataPrivilegeNoUserCode...");
        com.haier.openplatform.hac.service.HacDataPrivilegeAppDTO _searchHacDataPrivilegeNoUserCode_arg0 = null;
        java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> _searchHacDataPrivilegeNoUserCode__return = port.searchHacDataPrivilegeNoUserCode(_searchHacDataPrivilegeNoUserCode_arg0);
        System.out.println("searchHacDataPrivilegeNoUserCode.result=" + _searchHacDataPrivilegeNoUserCode__return);


        }
        {
        System.out.println("Invoking searchHacDataPrivilegeByUserCodeNoManager...");
        com.haier.openplatform.hac.service.HacDataPrivilegeAppDTO _searchHacDataPrivilegeByUserCodeNoManager_arg0 = null;
        java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> _searchHacDataPrivilegeByUserCodeNoManager__return = port.searchHacDataPrivilegeByUserCodeNoManager(_searchHacDataPrivilegeByUserCodeNoManager_arg0);
        System.out.println("searchHacDataPrivilegeByUserCodeNoManager.result=" + _searchHacDataPrivilegeByUserCodeNoManager__return);


        }
        {
        System.out.println("Invoking searchHacUserAndDataPrivilegeByApp...");
        com.haier.openplatform.hac.service.HacDataPrivilegeAppDTO _searchHacUserAndDataPrivilegeByApp_arg0 = null;
        java.util.List<com.haier.openplatform.hac.service.HacUserDataPrivilegeByAppDTO> _searchHacUserAndDataPrivilegeByApp__return = port.searchHacUserAndDataPrivilegeByApp(_searchHacUserAndDataPrivilegeByApp_arg0);
        System.out.println("searchHacUserAndDataPrivilegeByApp.result=" + _searchHacUserAndDataPrivilegeByApp__return);


        }
        {
        System.out.println("Invoking getPrivilegeDataByFzxDataId...");
        java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> _getPrivilegeDataByFzxDataId__return = port.getPrivilegeDataByFzxDataId();
        System.out.println("getPrivilegeDataByFzxDataId.result=" + _getPrivilegeDataByFzxDataId__return);


        }
        {
        System.out.println("Invoking searchHacDataPrivilegeByAppAndLeaf...");
        java.lang.String _searchHacDataPrivilegeByAppAndLeaf_arg0 = "";
        java.lang.String _searchHacDataPrivilegeByAppAndLeaf_arg1 = "";
        java.lang.String _searchHacDataPrivilegeByAppAndLeaf_arg2 = "";
        java.lang.String _searchHacDataPrivilegeByAppAndLeaf_arg3 = "";
        java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> _searchHacDataPrivilegeByAppAndLeaf__return = port.searchHacDataPrivilegeByAppAndLeaf(_searchHacDataPrivilegeByAppAndLeaf_arg0, _searchHacDataPrivilegeByAppAndLeaf_arg1, _searchHacDataPrivilegeByAppAndLeaf_arg2, _searchHacDataPrivilegeByAppAndLeaf_arg3);
        System.out.println("searchHacDataPrivilegeByAppAndLeaf.result=" + _searchHacDataPrivilegeByAppAndLeaf__return);


        }
        {
        System.out.println("Invoking getPrivilegeDataByFzxDataIdAndAppId...");
        java.lang.String _getPrivilegeDataByFzxDataIdAndAppId_arg0 = "";
        java.lang.Long _getPrivilegeDataByFzxDataIdAndAppId_arg1 = null;
        java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> _getPrivilegeDataByFzxDataIdAndAppId__return = port.getPrivilegeDataByFzxDataIdAndAppId(_getPrivilegeDataByFzxDataIdAndAppId_arg0, _getPrivilegeDataByFzxDataIdAndAppId_arg1);
        System.out.println("getPrivilegeDataByFzxDataIdAndAppId.result=" + _getPrivilegeDataByFzxDataIdAndAppId__return);


        }
        {
        System.out.println("Invoking getPrivilegeData1...");
        java.lang.String _getPrivilegeData1_arg0 = "";
        java.lang.String _getPrivilegeData1_arg1 = "";
        java.lang.String _getPrivilegeData1_arg2 = "";
        java.lang.String _getPrivilegeData1_arg3 = "";
        com.haier.openplatform.hac.service.UserSourceAndScode _getPrivilegeData1_arg4 = null;
        java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> _getPrivilegeData1__return = port.getPrivilegeData1(_getPrivilegeData1_arg0, _getPrivilegeData1_arg1, _getPrivilegeData1_arg2, _getPrivilegeData1_arg3, _getPrivilegeData1_arg4);
        System.out.println("getPrivilegeData1.result=" + _getPrivilegeData1__return);


        }
        {
        System.out.println("Invoking getResourceByAppUser...");
        java.lang.Long _getResourceByAppUser_arg0 = null;
        java.lang.String _getResourceByAppUser_arg1 = "";
        java.lang.String _getResourceByAppUser_arg2 = "";
        java.util.List<com.haier.openplatform.hac.service.HacResourceDTO> _getResourceByAppUser__return = port.getResourceByAppUser(_getResourceByAppUser_arg0, _getResourceByAppUser_arg1, _getResourceByAppUser_arg2);
        System.out.println("getResourceByAppUser.result=" + _getResourceByAppUser__return);


        }
        {
        System.out.println("Invoking getAllDataPrivilegeByApp...");
        java.lang.String _getAllDataPrivilegeByApp_arg0 = "";
        java.lang.String _getAllDataPrivilegeByApp_arg1 = "";
        java.lang.String _getAllDataPrivilegeByApp_arg2 = "";
        java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> _getAllDataPrivilegeByApp__return = port.getAllDataPrivilegeByApp(_getAllDataPrivilegeByApp_arg0, _getAllDataPrivilegeByApp_arg1, _getAllDataPrivilegeByApp_arg2);
        System.out.println("getAllDataPrivilegeByApp.result=" + _getAllDataPrivilegeByApp__return);


        }
        {
        System.out.println("Invoking getUserPosition...");
        java.lang.Long _getUserPosition_arg0 = null;
        java.util.List<com.haier.openplatform.hac.service.HacPositionInfoDTO> _getUserPosition__return = port.getUserPosition(_getUserPosition_arg0);
        System.out.println("getUserPosition.result=" + _getUserPosition__return);


        }
        {
        System.out.println("Invoking getResourceByAppUser1...");
        java.lang.String _getResourceByAppUser1_arg0 = "";
        java.lang.String _getResourceByAppUser1_arg1 = "";
        java.lang.String _getResourceByAppUser1_arg2 = "";
        java.util.List<com.haier.openplatform.hac.service.HacResourceDTO> _getResourceByAppUser1__return = port.getResourceByAppUser1(_getResourceByAppUser1_arg0, _getResourceByAppUser1_arg1, _getResourceByAppUser1_arg2);
        System.out.println("getResourceByAppUser1.result=" + _getResourceByAppUser1__return);


        }
        {
        System.out.println("Invoking getUserPosition1...");
        java.lang.String _getUserPosition1_arg0 = "";
        java.util.List<com.haier.openplatform.hac.service.HacPositionInfoDTO> _getUserPosition1__return = port.getUserPosition1(_getUserPosition1_arg0);
        System.out.println("getUserPosition1.result=" + _getUserPosition1__return);


        }

        System.exit(0);
    }

}
