package com.haier.openplatform.hac.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-09-17T16:05:11.832+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebService(targetNamespace = "http://service.hac.openplatform.haier.com/", name = "HacPrivilegeServiceClientPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface HacPrivilegeServiceClientPortType {

    @WebMethod
    @RequestWrapper(localName = "postponePrivilegesToUser", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.PostponePrivilegesToUser")
    @ResponseWrapper(localName = "postponePrivilegesToUserResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.PostponePrivilegesToUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult postponePrivilegesToUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6
    );

    @WebMethod
    @RequestWrapper(localName = "getPrivilegeData", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetPrivilegeData")
    @ResponseWrapper(localName = "getPrivilegeDataResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetPrivilegeDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> getPrivilegeData(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Long arg2
    );

    @WebMethod
    @RequestWrapper(localName = "searchHacDataPrivilegeByUserCode", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacDataPrivilegeByUserCode")
    @ResponseWrapper(localName = "searchHacDataPrivilegeByUserCodeResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacDataPrivilegeByUserCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> searchHacDataPrivilegeByUserCode(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.HacDataPrivilegeAppDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addUserDataPrivilege", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.AddUserDataPrivilege")
    @ResponseWrapper(localName = "addUserDataPrivilegeResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.AddUserDataPrivilegeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addUserDataPrivilege(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.haier.openplatform.hac.service.HacUserDataPrivilegeRelDTO> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getLastAppVerion", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetLastAppVerion")
    @ResponseWrapper(localName = "getLastAppVerionResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetLastAppVerionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getLastAppVerion(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchHacDataPrivilegeNoUserCode", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacDataPrivilegeNoUserCode")
    @ResponseWrapper(localName = "searchHacDataPrivilegeNoUserCodeResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacDataPrivilegeNoUserCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> searchHacDataPrivilegeNoUserCode(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.HacDataPrivilegeAppDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchHacDataPrivilegeByUserCodeNoManager", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacDataPrivilegeByUserCodeNoManager")
    @ResponseWrapper(localName = "searchHacDataPrivilegeByUserCodeNoManagerResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacDataPrivilegeByUserCodeNoManagerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> searchHacDataPrivilegeByUserCodeNoManager(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.HacDataPrivilegeAppDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchHacUserAndDataPrivilegeByApp", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacUserAndDataPrivilegeByApp")
    @ResponseWrapper(localName = "searchHacUserAndDataPrivilegeByAppResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacUserAndDataPrivilegeByAppResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacUserDataPrivilegeByAppDTO> searchHacUserAndDataPrivilegeByApp(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.HacDataPrivilegeAppDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getPrivilegeDataByFzxDataId", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetPrivilegeDataByFzxDataId")
    @ResponseWrapper(localName = "getPrivilegeDataByFzxDataIdResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetPrivilegeDataByFzxDataIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> getPrivilegeDataByFzxDataId();

    @WebMethod
    @RequestWrapper(localName = "searchHacDataPrivilegeByAppAndLeaf", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacDataPrivilegeByAppAndLeaf")
    @ResponseWrapper(localName = "searchHacDataPrivilegeByAppAndLeafResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacDataPrivilegeByAppAndLeafResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> searchHacDataPrivilegeByAppAndLeaf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "getPrivilegeDataByFzxDataIdAndAppId", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetPrivilegeDataByFzxDataIdAndAppId")
    @ResponseWrapper(localName = "getPrivilegeDataByFzxDataIdAndAppIdResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetPrivilegeDataByFzxDataIdAndAppIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> getPrivilegeDataByFzxDataIdAndAppId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getPrivilegeData1", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetPrivilegeData1")
    @ResponseWrapper(localName = "getPrivilegeData1Response", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetPrivilegeData1Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> getPrivilegeData1(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        com.haier.openplatform.hac.service.UserSourceAndScode arg4
    );

    @WebMethod
    @RequestWrapper(localName = "getResourceByAppUser", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetResourceByAppUser")
    @ResponseWrapper(localName = "getResourceByAppUserResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetResourceByAppUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacResourceDTO> getResourceByAppUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getAllDataPrivilegeByApp", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetAllDataPrivilegeByApp")
    @ResponseWrapper(localName = "getAllDataPrivilegeByAppResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetAllDataPrivilegeByAppResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacDataPrivilegeDTO> getAllDataPrivilegeByApp(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getUserPosition", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetUserPosition")
    @ResponseWrapper(localName = "getUserPositionResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetUserPositionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacPositionInfoDTO> getUserPosition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getResourceByAppUser1", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetResourceByAppUser1")
    @ResponseWrapper(localName = "getResourceByAppUser1Response", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetResourceByAppUser1Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacResourceDTO> getResourceByAppUser1(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getUserPosition1", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetUserPosition1")
    @ResponseWrapper(localName = "getUserPosition1Response", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetUserPosition1Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacPositionInfoDTO> getUserPosition1(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
