package com.haier.openplatform.hac.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-09-17T16:05:11.849+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebServiceClient(name = "HacPrivilegeServiceClient", 
                  wsdlLocation = "http://hac.haier.net:1030//com.haier.openplatform.hac.service.HacPrivilegeServiceClient?wsdl",
                  targetNamespace = "http://service.hac.openplatform.haier.com/") 
public class HacPrivilegeServiceClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.hac.openplatform.haier.com/", "HacPrivilegeServiceClient");
    public final static QName HacPrivilegeServiceClientPort = new QName("http://service.hac.openplatform.haier.com/", "HacPrivilegeServiceClientPort");
    static {
        URL url = null;
        try {
            url = new URL("http://hac.haier.net:1030//com.haier.openplatform.hac.service.HacPrivilegeServiceClient?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HacPrivilegeServiceClient.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://hac.haier.net:1030//com.haier.openplatform.hac.service.HacPrivilegeServiceClient?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HacPrivilegeServiceClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HacPrivilegeServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HacPrivilegeServiceClient() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HacPrivilegeServiceClient(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HacPrivilegeServiceClient(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HacPrivilegeServiceClient(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns HacPrivilegeServiceClientPortType
     */
    @WebEndpoint(name = "HacPrivilegeServiceClientPort")
    public HacPrivilegeServiceClientPortType getHacPrivilegeServiceClientPort() {
        return super.getPort(HacPrivilegeServiceClientPort, HacPrivilegeServiceClientPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HacPrivilegeServiceClientPortType
     */
    @WebEndpoint(name = "HacPrivilegeServiceClientPort")
    public HacPrivilegeServiceClientPortType getHacPrivilegeServiceClientPort(WebServiceFeature... features) {
        return super.getPort(HacPrivilegeServiceClientPort, HacPrivilegeServiceClientPortType.class, features);
    }

}
