package com.haier.openplatform.hac.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-09-17T16:01:11.284+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebService(targetNamespace = "http://service.hac.openplatform.haier.com/", name = "HacUserServiceCliPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface HacUserServiceCliPortType {

    @WebMethod
    @RequestWrapper(localName = "searchUserByData", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByData")
    @ResponseWrapper(localName = "searchUserByDataResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult searchUserByData(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.util.List<com.haier.openplatform.hac.service.HacAllInfoDTO> arg4
    );

    @WebMethod
    @RequestWrapper(localName = "searchMergeUsers", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchMergeUsers")
    @ResponseWrapper(localName = "searchMergeUsersResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchMergeUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult searchMergeUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.UserMergeDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteUserAuth", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.DeleteUserAuth")
    @ResponseWrapper(localName = "deleteUserAuthResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.DeleteUserAuthResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String deleteUserAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.HacUserCodeDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchUserByGroupIdOrGroupName", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByGroupIdOrGroupName")
    @ResponseWrapper(localName = "searchUserByGroupIdOrGroupNameResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByGroupIdOrGroupNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult searchUserByGroupIdOrGroupName(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.HacGroupDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchHacUserLoginLog", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacUserLoginLog")
    @ResponseWrapper(localName = "searchHacUserLoginLogResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacUserLoginLogResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult searchHacUserLoginLog(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "idsCheckAttributeUnique", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdsCheckAttributeUnique")
    @ResponseWrapper(localName = "idsCheckAttributeUniqueResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdsCheckAttributeUniqueResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult idsCheckAttributeUnique(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.UserIDSDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchUserByInfo", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByInfo")
    @ResponseWrapper(localName = "searchUserByInfoResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult searchUserByInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        com.haier.openplatform.hac.service.HacVariousList arg4
    );

    @WebMethod
    @RequestWrapper(localName = "exportUser", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.ExportUser")
    @ResponseWrapper(localName = "exportUserResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.ExportUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String exportUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchUserByDemain", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByDemain")
    @ResponseWrapper(localName = "searchUserByDemainResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByDemainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult searchUserByDemain(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        com.haier.openplatform.hac.service.HacVariList arg3
    );

    @WebMethod
    @RequestWrapper(localName = "searchAppAuth", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchAppAuth")
    @ResponseWrapper(localName = "searchAppAuthResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchAppAuthResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult searchAppAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "exportHacRole", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.ExportHacRole")
    @ResponseWrapper(localName = "exportHacRoleResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.ExportHacRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String exportHacRole(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchUserByGroupIdOrGroupNameForString", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByGroupIdOrGroupNameForString")
    @ResponseWrapper(localName = "searchUserByGroupIdOrGroupNameForStringResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByGroupIdOrGroupNameForStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String searchUserByGroupIdOrGroupNameForString(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.HacGroupDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "identifyInvalidUsers", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdentifyInvalidUsers")
    @ResponseWrapper(localName = "identifyInvalidUsersResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdentifyInvalidUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> identifyInvalidUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchSubUserByUserCode", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchSubUserByUserCode")
    @ResponseWrapper(localName = "searchSubUserByUserCodeResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchSubUserByUserCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult searchSubUserByUserCode(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchHacUser", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacUser")
    @ResponseWrapper(localName = "searchHacUserResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HacUserDTO> searchHacUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "idsActiveUser", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdsActiveUser")
    @ResponseWrapper(localName = "idsActiveUserResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdsActiveUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult idsActiveUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.UserIDSDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "validationData", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.ValidationData")
    @ResponseWrapper(localName = "validationDataResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.ValidationDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult validationData(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.UserMergeDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getUsersOfRole", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetUsersOfRole")
    @ResponseWrapper(localName = "getUsersOfRoleResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetUsersOfRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getUsersOfRole(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @RequestWrapper(localName = "validatGenerateRandomNum", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.ValidatGenerateRandomNum")
    @ResponseWrapper(localName = "validatGenerateRandomNumResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.ValidatGenerateRandomNumResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult validatGenerateRandomNum(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "searchMergeUserByUserName", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchMergeUserByUserName")
    @ResponseWrapper(localName = "searchMergeUserByUserNameResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchMergeUserByUserNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult searchMergeUserByUserName(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.UserMergeDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllUsersByName", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetAllUsersByName")
    @ResponseWrapper(localName = "getAllUsersByNameResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetAllUsersByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getAllUsersByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @RequestWrapper(localName = "searchHucUser", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHucUser")
    @ResponseWrapper(localName = "searchHucUserResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHucUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.HucUserDTO> searchHucUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "mergeUserLogin", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.MergeUserLogin")
    @ResponseWrapper(localName = "mergeUserLoginResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.MergeUserLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult mergeUserLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.UserMergeDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchHacUserByAppAndDate", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacUserByAppAndDate")
    @ResponseWrapper(localName = "searchHacUserByAppAndDateResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchHacUserByAppAndDateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult searchHacUserByAppAndDate(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "searchMergeUser", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchMergeUser")
    @ResponseWrapper(localName = "searchMergeUserResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchMergeUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult searchMergeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.UserMergeDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "mergeUserLoginDisabled", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.MergeUserLoginDisabled")
    @ResponseWrapper(localName = "mergeUserLoginDisabledResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.MergeUserLoginDisabledResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult mergeUserLoginDisabled(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.UserMergeDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchUserByDatas", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByDatas")
    @ResponseWrapper(localName = "searchUserByDatasResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.SearchUserByDatasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.SucOrErrDTO searchUserByDatas(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.ServiceClassDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getUserInfoByNickName", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetUserInfoByNickName")
    @ResponseWrapper(localName = "getUserInfoByNickNameResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetUserInfoByNickNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.service.DataGovUserDTO> getUserInfoByNickName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "idsUserLogout", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdsUserLogout")
    @ResponseWrapper(localName = "idsUserLogoutResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdsUserLogoutResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult idsUserLogout(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.UserIDSDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "idsResendActiveCode", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdsResendActiveCode")
    @ResponseWrapper(localName = "idsResendActiveCodeResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdsResendActiveCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult idsResendActiveCode(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.UserIDSDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getUsersOfPrivilege", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetUsersOfPrivilege")
    @ResponseWrapper(localName = "getUsersOfPrivilegeResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.GetUsersOfPrivilegeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getUsersOfPrivilege(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @RequestWrapper(localName = "idsFindUserBySSOID", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdsFindUserBySSOID")
    @ResponseWrapper(localName = "idsFindUserBySSOIDResponse", targetNamespace = "http://service.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.service.IdsFindUserBySSOIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.service.ExecuteResult idsFindUserBySSOID(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.service.UserIDSDTO arg0
    );
}
