package com.haier.openplatform.hac.resource.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-09-17T15:41:10.070+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebService(targetNamespace = "http://service.resource.hac.openplatform.haier.com/", name = "HacResourceServiceClientPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface HacResourceServiceClientPortType {

    @WebMethod
    @RequestWrapper(localName = "getResourceById", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetResourceById")
    @ResponseWrapper(localName = "getResourceByIdResponse", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetResourceByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.resource.service.HacResourceDTO getResourceById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getAppMarketList", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetAppMarketList")
    @ResponseWrapper(localName = "getAppMarketListResponse", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetAppMarketListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.openplatform.hac.resource.service.Pager getAppMarketList(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haier.openplatform.hac.resource.service.AppMarketQuery arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getGroupByUserAndAppId", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetGroupByUserAndAppId")
    @ResponseWrapper(localName = "getGroupByUserAndAppIdResponse", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetGroupByUserAndAppIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.resource.service.HacGroupDTO> getGroupByUserAndAppId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "getAppMarketLeftTree", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetAppMarketLeftTree")
    @ResponseWrapper(localName = "getAppMarketLeftTreeResponse", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetAppMarketLeftTreeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.resource.service.TreeNode> getAppMarketLeftTree(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Long arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @RequestWrapper(localName = "getTodoTask", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetTodoTask")
    @ResponseWrapper(localName = "getTodoTaskResponse", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetTodoTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.resource.service.HacResourceModelDTO> getTodoTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "getResourceFileBytes", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetResourceFileBytes")
    @ResponseWrapper(localName = "getResourceFileBytesResponse", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetResourceFileBytesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public byte[] getResourceFileBytes(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getResourcesByAppAndUser", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetResourcesByAppAndUser")
    @ResponseWrapper(localName = "getResourcesByAppAndUserResponse", targetNamespace = "http://service.resource.hac.openplatform.haier.com/", className = "com.haier.openplatform.hac.resource.service.GetResourcesByAppAndUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.haier.openplatform.hac.resource.service.HacResourceDTO> getResourcesByAppAndUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        com.haier.openplatform.hac.resource.service.UserSourceAndScode arg4
    );
}
