package com.haier.openplatform.hac.resource.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-09-17T15:41:10.081+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebServiceClient(name = "HacResourceServiceClient", 
                  wsdlLocation = "http://hac.haier.net:1033/com.haier.openplatform.hac.resource.service.HacResourceServiceClient?wsdl",
                  targetNamespace = "http://service.resource.hac.openplatform.haier.com/") 
public class HacResourceServiceClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.resource.hac.openplatform.haier.com/", "HacResourceServiceClient");
    public final static QName HacResourceServiceClientPort = new QName("http://service.resource.hac.openplatform.haier.com/", "HacResourceServiceClientPort");
    static {
        URL url = null;
        try {
            url = new URL("http://hac.haier.net:1033/com.haier.openplatform.hac.resource.service.HacResourceServiceClient?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HacResourceServiceClient.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://hac.haier.net:1033/com.haier.openplatform.hac.resource.service.HacResourceServiceClient?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HacResourceServiceClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HacResourceServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HacResourceServiceClient() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HacResourceServiceClient(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HacResourceServiceClient(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HacResourceServiceClient(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns HacResourceServiceClientPortType
     */
    @WebEndpoint(name = "HacResourceServiceClientPort")
    public HacResourceServiceClientPortType getHacResourceServiceClientPort() {
        return super.getPort(HacResourceServiceClientPort, HacResourceServiceClientPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HacResourceServiceClientPortType
     */
    @WebEndpoint(name = "HacResourceServiceClientPort")
    public HacResourceServiceClientPortType getHacResourceServiceClientPort(WebServiceFeature... features) {
        return super.getPort(HacResourceServiceClientPort, HacResourceServiceClientPortType.class, features);
    }

}
